andoBuscando/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path("login/", auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path('usuario/', include('apps.usuario.urls'), name='usuario'),
    path('publicacion/', include('apps.publicacion.urls'), name='publicacion'),
    path('terminos/', include('apps.publicacion.urls'), name='terminos'),
    path('contacto/', include('apps.publicacion.urls'), name='contacto'),
    path('faq/', include('apps.publicacion.urls'), name='faq'),
    path('propiedad/', include('apps.propiedad.urls'), name='propiedad'),
    path('contador/', include('apps.contador.urls'), name='contador'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/publicacion/urls.py
from django.urls import path
from apps.publicacion.views import PublicacionListView, DashboardView, PublicacionCargaView, ContactarUsuarioView, PublicacionEdicionView, PublicacionEliminacionView, PoliticasView, ContactoView, FaqView
from . import views

urlpatterns=[
    path("busquedas/", PublicacionListView.as_view(), name="busquedas"),
    path("acciones_usuario/", DashboardView.as_view(), name="acciones_usuario"),
    path("cargar_publicacion/", PublicacionCargaView.as_view(), name="cargar_publicacion"),
    path("contactar_usuario/", ContactarUsuarioView.as_view() , name="contactar_usuario"),
    path("editar_publicacion/<int:pk>/", PublicacionEdicionView.as_view(),name="editar_publicacion"),
    path("eliminar_publicacion/<int:pk>/", PublicacionEliminacionView.as_view(), name="eliminar_publicacion"),
    path("politicas/", PoliticasView.as_view(), name="politicas"),
    path("contacto/", ContactoView.as_view(), name="contacto"),
    path("faq/", FaqView.as_view(), name="faq"),
]

apps/publicacion/models.py
from django.db import models

class Publicacion(models.Model):
    cliente = models.ForeignKey('usuario.Usuario', on_delete=models.CASCADE)
    barrio = models.CharField(max_length=25)
    tipo_propiedad = models.ForeignKey('propiedad.TipoPropiedad', on_delete=models.CASCADE)
    tipo_operacion = models.ForeignKey('propiedad.TipoOperacion', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=40)
    ambientes = models.PositiveIntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    moneda = models.CharField(max_length=30)
    descripcion = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo

class AgentePublicacion(models.Model):
    agente = models.ForeignKey('usuario.Usuario', on_delete=models.CASCADE)
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE)    

    def __str__(self):
        return f"{self.agente} - {self.publicacion.titulo}"

class PublicacionTipoOper(models.Model):
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE)
    tipo_operacion = models.ForeignKey('propiedad.TipoOperacion', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.publicacion.titulo} - {self.tipo_operacion}"

class PublicacionTipoProp(models.Model):
    publicacion =  models.ForeignKey(Publicacion, on_delete=models.CASCADE)
    tipo_propiedad =  models.ForeignKey('propiedad.TipoPropiedad', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.publicacion.titulo} - {self.tipo_propiedad}"

apps/publicacion/forms.py
from django import forms
from apps.publicacion.models import Publicacion
from decimal import Decimal

class CargarPublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacion
        fields = ['titulo', 'moneda', 'ambientes', 'descripcion', 'barrio', 'tipo_propiedad', 'tipo_operacion', 'precio']

class EditarPublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacion
        fields = ['titulo', 'moneda', 'ambientes', 'descripcion', 'barrio', 'tipo_propiedad', 'tipo_operacion', 'precio']

class BuscarPublicacionesForm(forms.ModelForm):
    min_precio = forms.DecimalField(required=False, label="Precio mínimo")
    max_precio = forms.DecimalField(required=False, label="Precio máximo")

    class Meta:
        model = Publicacion
        fields = ['barrio', 'tipo_operacion', 'tipo_propiedad']

apps/publicacion/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView # Importamos CreateView
from apps.publicacion.models import Publicacion
from apps.publicacion.forms import CargarPublicacionForm, EditarPublicacionForm # Importamos el formulario CargarPublicacionForm que se utiliza para crear publicaciones.
from django.urls import reverse_lazy # Importamos del modelo de urls el método de redirección
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.shortcuts import Http404, get_object_or_404

# Vista para listar publicaciones hechas por cualquier usuario
class PublicacionListView(ListView):
    model = Publicacion
    template_name = "lista_publicaciones.html"
    context_object_name = "publicaciones"
    paginate_by = 12

    def get_queryset(self):
        # Obtener los parámetros de la URL (GET)
        tipo_propiedad = self.request.GET.get('tipo_propiedad')
        barrio = self.request.GET.get('barrio')
        tipo_operacion = self.request.GET.get('tipo_operacion')
        moneda = self.request.GET.get('moneda')
        min_precio = self.request.GET.get('min_precio')
        max_precio = self.request.GET.get('max_precio')
        min_metros_cuadrados = self.request.GET.get('metros_cuadrados')
        min_ambientes = self.request.GET.get('ambientes')

        # Si hay al menos un filtro, aplicar normalmente
        queryset = Publicacion.objects.all()

        # Filtrar según los parámetros disponibles
        if tipo_propiedad:
            queryset = queryset.filter(tipo_propiedad=tipo_propiedad)
        if barrio:
            queryset = queryset.filter(barrio=barrio)
        if tipo_operacion:
            queryset = queryset.filter(tipo_operacion=tipo_operacion)
        if moneda:
            queryset = queryset.filter(moneda__icontains=moneda)
        if min_precio:
            queryset = queryset.filter(precio__gte=min_precio)
        if max_precio:
            queryset = queryset.filter(precio__lte=max_precio)
        if min_metros_cuadrados:
            min_metros_cuadrados = min_metros_cuadrados.strip('[]').split(',')
            if len(min_metros_cuadrados) == 2:
                min_metros = int(min_metros_cuadrados[0])
                max_metros = int(min_metros_cuadrados[1])
                queryset = queryset.filter(metros_cuadrados__gte=min_metros, metros_cuadrados__lte=max_metros)
        if min_ambientes:
            min_ambientes = min_ambientes.strip('[]').split(',')
            if len(min_ambientes) == 2:
                min_amb = int(min_ambientes[0])
                max_amb = int(min_ambientes[1])
                queryset = queryset.filter(ambientes__gte=min_amb, ambientes__lte=max_amb)

        # Ordenar según los parámetros 'orderby' y 'order' si existen
        order_by = self.request.GET.get('orderby', 'fecha_creacion')  # por defecto por fecha de creación
        order = self.request.GET.get('order', 'ASC')  # por defecto en orden ascendente

        if order == 'ASC':
            queryset = queryset.order_by(order_by)
        else:
            queryset = queryset.order_by(f'-{order_by}')

        return queryset
        
# Vista de acciones usuario
class DashboardView(LoginRequiredMixin, ListView):
    model = Publicacion
    template_name = "acciones_usuario.html"
    context_object_name = 'publicaciones'

    def get_queryset(self):
        return Publicacion.objects.filter(cliente=self.request.user)

# Vista para cargar busquedas
class PublicacionCargaView(LoginRequiredMixin, CreateView):
    model = Publicacion
    form_class = CargarPublicacionForm
    template_name = 'carga_publicacion.html'
    success_url = reverse_lazy('acciones_usuario')  

    # Redirigir a la URL de login si no está logueado
    login_url = reverse_lazy('login') 

    def form_valid(self, form):
        form.instance.cliente = self.request.user
        return super().form_valid(form)
    
# Vista para el "chat de contacto"    
class ContactarUsuarioView(LoginRequiredMixin,TemplateView):
    template_name = 'contactar_usuario.html'
    login_url = "/login/"
    redirect_field_name = "redirect_to"
    raise_exception = False

    def get(self,request):
        return self.render_to_response({})
    
# Vista para editar publicaciones
class PublicacionEdicionView(UpdateView):
    model = Publicacion
    form_class = EditarPublicacionForm
    template_name = 'editar_publicacion.html'
    success_url = reverse_lazy('acciones_usuario')

    def get_object(self):
        try:
            publicacion = Publicacion.objects.get(pk=self.kwargs['pk'], cliente=self.request.user)
        except Publicacion.DoesNotExist:
            messages.error(self.request, 'Publicación no encontrada.')
            raise Http404("Publicación no encontrada")
        return publicacion
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

# Vista para eliminar publicaciones  
class PublicacionEliminacionView(DeleteView):
    model = Publicacion
    template_name='eliminar_publicacion.html'
    success_url = reverse_lazy ('acciones_usuario')

    def get_object(self):
        publicacion = get_object_or_404(Publicacion, pk=self.kwargs['pk'], cliente=self.request.user)
        return publicacion
    
    def delete(self, request, *args, **kwargs):
        publicacion = self.get_object()
        publicacion.delete()
        return redirect(self.success_url)

class PoliticasView(TemplateView):
    template_name = 'politicas.html'
    redirect_field_name = "redirect_to"
    raise_exception = False

    def get(self,request):
        return self.render_to_response({})
    

class ContactoView(TemplateView):
    template_name = 'contacto.html'
    redirect_field_name = "redirect_to"
    raise_exception = False

    def get(self,request):
        return self.render_to_response({})


class FaqView(TemplateView):
    template_name = 'faq.html'
    redirect_field_name = "redirect_to"
    raise_exception = False

    def get(self,request):
        return self.render_to_response({})

apps/publicacion/templates/CRUD_publicaciones.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ANDO BUSCANDO | Búsquedas{% endblock %}

{% block content %}

<div class="content-area blog-page padding-top-40" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">   
        <div class="row">
            <div class="blog-lst col-md-12">
                <section class="post">
                    <div class="text-center padding-b-50">
                        <h2 class="wow fadeInLeft animated">Podras realizar las siguientes acciones</h2>
                        <div class="title-line wow fadeInRight animated"></div>
                    </div>
                    <br><br>
                    <p class="intro">En este espacio podrás cargar la información referida a tu búsqueda.</p>
                        <a href="single.html" class="btn btn-default btn-border">Crear búsqueda</a>
                </section>   

                <section class="post">
                    <div class="text-center padding-b-50">
                        <div class="title-line wow fadeInRight animated"></div>
                    </div>
                    <p class="intro">Si su publicación requiere alguna modificación, aquí es donde podrá hacerla.</p>
                        <a href="single.html" class="btn btn-default btn-border">Editar búsqueda</a>
                </section>  

                <section class="post">
                    <div class="text-center padding-b-50">
                        <div  class="title-line wow fadeInRight animated"></div>
                    </div>
                    <p class="intro">En caso de necesitar borrar una publicación deberá ingresar a este espacio.</p>
                        <a href="single.html" class="btn btn-default btn-border">Eliminar búsqueda</a>
                </section>

                <section class="post">
                    <div class="text-center padding-b-50">
                        <div  class="title-line wow fadeInRight animated"></div>
                    </div>
                    <p class="intro">Si preferís podes ingresar a ver las propiedades publicadas hasta el momento.</p>
                        <a href="single.html" class="btn btn-default btn-border">Listado de propiedades</a>
                </section>

            </div>  
        </div>
    </div>
</div>

{% endblock %}

apps/publicacion/templates/acciones_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ANDO BUSCANDO | Acciones Usuario{% endblock %}

{% block content %}
        <div class="page-head"> 
            <div class="container">
                <div class="row">
                    <div class="page-head-content">
                        <h2 class="wow fadeInLeft animated">Desde aquí podrás manejar tus búsquedas</h2>
                        <div class="title-line wow fadeInRight animated"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-area submit-property" style="background-color: #FCFCFC;">&nbsp;
            <div class="container">
                <div class="clearfix" > 
                    <div class="wizard-container">         
                    {% if publicaciones %}
                        <div class="row">
                            {% for publicacion in publicaciones %}
                                <div class="col-sm-6 col-md-4 col-lg-3 p-3">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="item-entry overflow">
                                                <h5 class="card-title">{{ publicacion.titulo }}</h5>
                                                <div class="dot-hr"></div>
                                                <p class="card-text">{{ publicacion.descripcion }}</p>
                                                <a href="{% url 'editar_publicacion' pk=publicacion.pk %}" class="btn btn-default">Editar</a>
                                                <a href="{% url 'eliminar_publicacion' pk=publicacion.pk %}" class="btn btn-danger">Eliminar</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p>No tienes publicaciones.</p>
                    {% endif %}
                    <br>
                    <a href="{% url 'cargar_publicacion' %}" class="btn btn-primary">Crear publicación</a>
                    </div>  
                </div>
            </div>
        </div>

{% endblock %}

apps/publicacion/templates/contactar_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ANDO BUSCANDO | Contactar Usuario{% endblock %}

{% block content %}

 <div class="page-head"> 
            <div class="container">
                <div class="row">
                    <div class="page-head-content">
                        <h1 class="page-title">Contactar Usuario</h1>               
                    </div>
                </div>
            </div>
        </div>
        <!-- End page header -->

        <!-- property area -->
        <div class="content-area recent-property padding-top-40" style="background-color: #FFF;">
            <div class="container">  
                <div class="row">
                    <div class="col-md-8 col-md-offset-2"> 
                        <div class="" id="contact1">                        
                            <div class="row">
                           
                            </div>
                            <!-- /.row -->
                            
                            <h2>Chat</h2>
                            <form>
                                <div class="row">                                
                                    <div class="col-sm-12">
                                        <div >
                                            <label for="subject">Título</label>
                                            <input type="text" class="form-control" id="subject">
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="message">Mensaje</label>
                                            <textarea id="message" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-sm-12 text-center">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Enviar mensaje</button>
                                    </div>
                                </div>
                                <!-- /.row -->
                            </form>
                        </div>
                    </div>    
                </div>
            </div>
        </div>

{% endblock %}

apps/publicacion/templates/editar_publicacion.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ANDO BUSCANDO | Editar Publicacion{% endblock %}

{% block content %}

<div class="page-head"> 
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Edita una búsqueda</h1>               
            </div>
        </div>
    </div>
</div>
<!-- End page header -->
<div class="content-area submit-property" style="background-color: #FCFCFC;">&nbsp;
    <div class="container">
        <div class="clearfix" > 
            <div class="wizard-container"> 

                <div class="wizard-card ct-wizard-orange" id="wizardProperty">
                    <!-- <form action="" method=""> -->
                    <form method="post" action="{% url 'editar_publicacion' pk=publicacion.pk %}" enctype="multipart/form-data">
                        {% csrf_token %} 
                        <!-- Errores del formulario -->
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                <ul>
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <li><strong>{{ field.label }}:</strong>
                                                {% for error in field.errors %}
                                                    {{ error }}
                                                {% endfor %}
                                            </li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                                   
                        <div class="wizard-header">
                            <h3>
                                <b>Edita</b> TU PUBLICACION <br>
                                <small>En tres simples pasos podras actualizarla</small>
                            </h3>
                        </div>

                        <ul>
                            <li><a href="#step1" data-toggle="tab">Paso 1 </a></li>
                            <li><a href="#step2" data-toggle="tab">Paso 2 </a></li>
                            <li><a href="#step3" data-toggle="tab">Finalizar </a></li>
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane" id="step1">
                                <div class="row p-b-15  ">
                                    <h4 class="info-text"> Empecemos con la informacion básica</h4>

                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label>Título <small>(requerido)</small></label>
                                            <input name="titulo" type="text" class="form-control" value="{{ publicacion.titulo }}" placeholder="Departamento 2 ambientes..." required>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_moneda">Precio :</label>
                                            <select name='moneda' class="form-control" value="{{ publicacion.moneda }}">
                                                <!-- <option disabled selected> Moneda </option> -->
                                                <option value="USD" {% if publicacion.moneda == 'USD' %}selected{% endif %}>Dolar Estadounidense (USD)</option>
                                                <option value="ARS" {% if publicacion.moneda == 'ARS' %}selected{% endif %}>Pesos Argentinos(ARS)</option> 
                                            </select>
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Precio máximo <small>(requerido)</small></label>
                                            <input name="precio" type="number" class="form-control" value="{{ publicacion.precio }}" required>


                                        </div>
                                        <div class="form-group">
                                            <label for="id_tipo_operacion">Tipo operacion:</label>
                                            <select name="tipo_operacion" id="id_tipo_operacion" class="form-control">
                                                <option value="" selected>---------</option>
                                                {% for tipo in form.tipo_operacion.field.queryset %}
                                                    <option value="{{ tipo.id }}" {% if tipo.id == publicacion.tipo_operacion.id %}selected{% endif %}>
                                                        {{ tipo.tipo_operacion }}
                                                    </option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--  End step 1 -->

                            <div class="tab-pane" id="step2">
                                <h4 class="info-text"> Detalles de tu búsqueda </h4>
                                <div class="row">
                                    <div class="col-sm-12"> 
                                        <div class="col-sm-12"> 
                                            <div class="form-group">
                                                <label>Descripción :</label>
                                                <textarea name="descripcion" class="form-control" >{{ publicacion.descripcion }}</textarea>
                                            </div> 
                                        </div> 
                                    </div>

                                    <div class="col-sm-12">
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <label for="id_barrio">Barrio:</label>
                                                <select name="barrio" id="barrio-select" class="selectpicker" data-live-search="true" data-live-search-style="begins" value="{{ publicacion.barrio }}">
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <label for="id_tipo_propiedad">Tipo propiedad:</label>
                                                <select name="tipo_propiedad" required id="id_tipo_propiedad" class="form-control" value="{{ publicacion.tipo_propiedad }}">
                                                <!-- <option value="" selected>---------</option> -->
                                                {% for tipo in form.tipo_propiedad.field.queryset %}
                                                <option value="{{ tipo.id }}" {% if tipo.id == publicacion.tipo_propiedad.id %}selected{% endif %}>
                                                    {{ tipo.tipo_propiedad }} <!-- Asumiendo que 'tipo_propiedad' es el campo que deseas mostrar -->
                                                </option>
                                                {% endfor %}
                                            
                                            </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <label for="price-range">Ambientes:</label>
                                                <input name="ambientes" type="text" class="span2" value="{{ publicacion.ambientes }}" data-slider-min="0" 
                                                        data-slider-max="20" data-slider-step="1" 
                                                        data-slider-value="{{ publicacion.ambientes }}" id="min-baths" ><br />
                                                <b class="pull-left color">1</b> 
                                                <b class="pull-right color">20</b>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="col-sm-12">
                                        <div class="col-sm-6">
                                            <div class="form-group"></div>
                                        </div>
                                    </div>
                                    <br>
                                </div>
                            </div>
                            <!-- End step 2 -->

                            <div class="tab-pane" id="step3">                                        
                                <h4 class="info-text"> Actualizar publicación </h4>
                                
                            <!--  End step 4 -->

                        </div>

                        <div class="wizard-footer">
                            <div class="pull-right">
                                <input type='button' class='btn btn-next btn-primary' name='next' value='Siguiente' />
                                <input type='submit' class='btn btn-finish btn-primary ' name='finish' value='Confirmar cambios' />
                            </div>

                            <div class="pull-left">
                                <input type='button' class='btn btn-previous btn-default' name='previous' value='Anterior' />
                            </div>
                            <div class="clearfix"></div>                                            
                        </div>	
                    </form>
                </div>
                <!-- End submit form -->
            </div>
            <a class="btn btn-secondary" href="{% url 'acciones_usuario' %}"> << VOLVER </a> 
        </div>
    </div>
</div>
{% endblock %}

apps/publicacion/templates/eliminar_publicacion.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ANDO BUSCANDO | Eliminar Publicacion{% endblock %}

{% block content %}

<div class="properties-area recent-property" style="background-color: #FFF;">
    <div class="container"> 
        <div class="row  pr0 padding-top-40 properties-page">
            <div class="col-md-6 padding-bottom-40 large-search"> 
                <div class="search-form wow pulse" style="text-align: center;" data-wow-delay="0.8s">
                    <div class="form-inline">
                        <div class="col-md-8">
                            <div class="form-group">     
                                <div class="item-entry overflow">
                                    <h5>Confirmar eliminación</h5>
                                    <div class="dot-hr"></div>
                                    <p class="card-text">¿Estás seguro de que deseas eliminar esta publicación?</p>
                                    <h6 class="card-subtitle mb-2 text-muted">{{ publicacion.titulo }}</h6>
                                    <p class="card-text">{{ publicacion.descripcion }}</p>
                                    <form method="post"> 
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Eliminar</button>
                                        <a href="{% url 'acciones_usuario' %}" class="btn btn-default">Cancelar</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                
{% endblock %}