andoBuscando/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path("login/", auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path('usuario/', include('apps.usuario.urls'), name='usuario'),
    path('publicacion/', include('apps.publicacion.urls'), name='publicacion'),
    path('terminos/', include('apps.publicacion.urls'), name='terminos'),
    path('contacto/', include('apps.publicacion.urls'), name='contacto'),
    path('faq/', include('apps.publicacion.urls'), name='faq'),
    path('propiedad/', include('apps.propiedad.urls'), name='propiedad'),
    path('contador/', include('apps.contador.urls'), name='contador'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/propiedad/urls.py
from django.urls import path
from apps.propiedad.views import PropiedadView, PropiedadDetalleView, CrearPropiedadView, ContactarAgenteView, PropieadadActualizarView, EliminarPropiedadView, MisPropiedadesView
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns=[
    path("",PropiedadView.as_view(), name="propiedades"),
    path("cargar_propiedad/",CrearPropiedadView.as_view(), name="cargar_propiedad"),
    path("detalles_propiedad/<int:pk>/",PropiedadDetalleView.as_view(), name="detalles_propiedad"),
    path("contactar_agente", ContactarAgenteView.as_view() , name="contactar_agente"),
    path("editar_propiedad/<int:pk>",PropieadadActualizarView.as_view(), name="editar_propiedad" ),
    path("eliminar_propiedad/<int:pk>",EliminarPropiedadView.as_view(), name="eliminar_propiedad" ),
    path("mis_propiedades/",MisPropiedadesView.as_view(), name="mis_propiedades" ),
    path('api/barrios/', views.obtener_barrios, name='obtener_barrios'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/propiedad/models.py
from django.db import models
from cloudinary.models import CloudinaryField

class Propiedad(models.Model):
    barrio = models.CharField(max_length=25)
    agente = models.ForeignKey('usuario.Usuario', on_delete=models.CASCADE)
    tipo_propiedad = models.ForeignKey('propiedad.TipoPropiedad', on_delete=models.CASCADE)
    tipo_operacion = models.ForeignKey('propiedad.TipoOperacion', on_delete=models.CASCADE)
    titulo= models.CharField(max_length=50, default='sin titulo')
    foto = CloudinaryField('images', null=True, blank=True)
    ambientes = models.PositiveIntegerField()
    metros_cuadrados = models.PositiveIntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    moneda = models.CharField(max_length=30)
    direccion = models.CharField(max_length=55)
    descripcion = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True) 

class TipoOperacion(models.Model):
    tipo_operacion = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.tipo_operacion

class TipoPropiedad(models.Model):
    tipo_propiedad = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.tipo_propiedad
    
class PropiedadFoto(models.Model):
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE)
    ubicacion_url = models.URLField(max_length=255)
    descripcion_foto = models.CharField(max_length=255)

    def __str__(self):
        return f"Foto de {self.propiedad} - {self.descripcion_foto}"

apps/propiedad/forms.py
from django import forms
from cloudinary.forms import CloudinaryFileField
from apps.propiedad.models import Propiedad


class CrearPropiedadForm(forms.ModelForm):
    foto = CloudinaryFileField()
    class Meta:
        model = Propiedad
        fields = ['titulo','foto','moneda','precio','tipo_operacion','descripcion','barrio','direccion','tipo_propiedad','ambientes','metros_cuadrados']


class EditarPropiedadForm(forms.ModelForm):
    class Meta:
        model = Propiedad
        fields = ['titulo','foto','moneda','precio','tipo_operacion','descripcion','barrio','direccion','tipo_propiedad','ambientes','metros_cuadrados']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Hacer que los campos no sean obligatorios
        for field in self.fields:
            if self.instance and getattr(self.instance, field):
                self.fields[field].required = False
    
    def clean_titulo(self):
        titulo = self.cleaned_data.get('titulo')
        if not titulo:
            return self.instance.titulo  # Mantiene el valor
        return titulo

    def clean_foto(self):
        foto = self.cleaned_data.get('foto')
        if not foto:
            return self.instance.foto
        return foto
    
    def clean_moneda(self):
        moneda = self.cleaned_data.get('moneda')
        if not moneda:
            return self.instance.moneda 
        return moneda
    
    def clean_precio(self):
        precio = self.cleaned_data.get('precio')
        if not precio:
            return self.instance.precio 
        return precio
    
    def clean_tipo_operacion(self):
        tipo_operacion = self.cleaned_data.get('tipo_operacion')
        if not tipo_operacion:
            return self.instance.tipo_operacion
        return tipo_operacion
    
    def clean_descripcion(self):
        descripcion = self.cleaned_data.get('descripcion')
        if not descripcion:
            return self.instance.descripcion
        return descripcion

    def clean_barrio(self):
        barrio = self.cleaned_data.get('barrio')
        if not barrio:
            return self.instance.barrio
        return barrio

    def clean_direccion(self):
        direccion = self.cleaned_data.get('direccion')
        if not direccion:
            return self.instance.direccion
        return direccion

    def clean_tipo_propiedad(self):
        tipo_propiedad = self.cleaned_data.get('tipo_propiedad')
        if not tipo_propiedad:
            return self.instance.tipo_propiedad
        return tipo_propiedad
    
    def clean_ambientes(self):
        ambientes = self.cleaned_data.get('ambientes')
        if not ambientes:
            return self.instance.ambientes
        return ambientes

    def clean_metros_cuadrados(self):
        metros_cuadrados = self.cleaned_data.get('metros_cuadrados')
        if not metros_cuadrados:
            return self.instance.metros_cuadrados
        return metros_cuadrados


class BuscarPropiedadForm(forms.ModelForm):
    min_precio = forms.DecimalField(required=False, label="Precio mínimo")
    max_precio = forms.DecimalField(required=False, label="Precio máximo")
    min_metros_cuadrados = forms.IntegerField(required=False, label="Mínimo m²")
    max_metros_cuadrados = forms.IntegerField(required=False, label="Máximo m²")
    min_ambientes = forms.IntegerField(required=False, label="Mínimo ambientes")
    max_ambientes = forms.IntegerField(required=False, label="Máximo ambientes")

    class Meta:
        model = Propiedad
        fields = ['barrio', 'tipo_operacion', 'moneda','tipo_propiedad' ]
        

apps/propiedad/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView, FormView
from apps.propiedad.models import Propiedad
from apps.propiedad.forms import CrearPropiedadForm, EditarPropiedadForm
from django.contrib import messages
from django.conf import settings
from PIL import Image
import io
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.contrib.auth.mixins import LoginRequiredMixin
import requests
from django.http import JsonResponse

# Create your views here.
class PropiedadView(ListView):
    model = Propiedad
    template_name = 'propiedades.html'
    context_object_name = 'propiedades'
    paginate_by = 12  # Paginación de 10 resultados por página


    def get_queryset(self):
        # Obtener los parámetros de la URL (GET)
        tipo_propiedad = self.request.GET.get('tipo_propiedad')
        barrio = self.request.GET.get('barrio')
        tipo_operacion = self.request.GET.get('tipo_operacion')
        moneda = self.request.GET.get('moneda')
        min_precio = self.request.GET.get('min_precio')
        max_precio = self.request.GET.get('max_precio')
        min_metros_cuadrados = self.request.GET.get('metros_cuadrados')
        min_ambientes = self.request.GET.get('ambientes')

        # Si hay al menos un filtro, aplicar normalmente
        queryset = Propiedad.objects.all()

        # Filtrar según los parámetros disponibles
        if tipo_propiedad:
            queryset = queryset.filter(tipo_propiedad=tipo_propiedad)
        if barrio:
            queryset = queryset.filter(barrio=barrio)
        if tipo_operacion:
            queryset = queryset.filter(tipo_operacion=tipo_operacion)
        if moneda:
            queryset = queryset.filter(moneda__icontains=moneda)
        if min_precio:
            queryset = queryset.filter(precio__gte=min_precio)
        if max_precio:
            queryset = queryset.filter(precio__lte=max_precio)
        if min_metros_cuadrados:
            min_metros_cuadrados = min_metros_cuadrados.strip('[]').split(',')
            if len(min_metros_cuadrados) == 2:
                min_metros = int(min_metros_cuadrados[0])
                max_metros = int(min_metros_cuadrados[1])
                queryset = queryset.filter(metros_cuadrados__gte=min_metros, metros_cuadrados__lte=max_metros)
        if min_ambientes:
            min_ambientes = min_ambientes.strip('[]').split(',')
            if len(min_ambientes) == 2:
                min_amb = int(min_ambientes[0])
                max_amb = int(min_ambientes[1])
                queryset = queryset.filter(ambientes__gte=min_amb, ambientes__lte=max_amb)

        # Ordenar según los parámetros 'orderby' y 'order' si existen
        order_by = self.request.GET.get('orderby', 'fecha_creacion')  # por defecto por fecha de creación
        order = self.request.GET.get('order', 'ASC')  # por defecto en orden ascendente

        if order == 'ASC':
            queryset = queryset.order_by(order_by)
        else:
            queryset = queryset.order_by(f'-{order_by}')

        return queryset

class CrearPropiedadView(CreateView):
    model = Propiedad
    form_class = CrearPropiedadForm 
    template_name = 'carga_propiedad.html'
    success_url = reverse_lazy('propiedades') 
    def dispatch(self, request, *args, **kwargs):
        # Verificar si el usuario es un agente
        if not request.user.is_agente:
            messages.error(request, "Solo los agentes pueden crear propiedades.")
            return redirect('propiedades')  # Redirige a la lista de propiedades si no tiene permiso

        return super().dispatch(request, *args, **kwargs)
    def form_valid(self, form):
        form.instance.agente = self.request.user
        messages.success(self.request, 'Se cargo la propiedad, ya puede visualizarlo.')
        propiedad = form.save(commit=False)
        #imagen = self.request.FILES.get('foto') 

       

        propiedad.save()  # Guardar el modelo con la imagen procesada
        return super().form_valid(form)

class PropiedadDetalleView(DetailView):
    model = Propiedad
    template_name = "detalle_propiedad.html"
    context_object_name = 'propiedad'
    

class PropieadadActualizarView(LoginRequiredMixin,UpdateView):
    model = Propiedad
    form_class = EditarPropiedadForm
    template_name = "editar_propiedad.html"
    success_url = reverse_lazy('mis_propiedades')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Actualizaste la informacion de tu propiedad correctamente.')
        return super().form_valid(form)
    
    def dispatch(self, request, *args, **kwargs):
        propiedad = self.get_object()

        # Verifica si el usuario tiene permisos para editar la propiedad
        if not request.user.is_agente:  # Verifica si es un agente
            messages.error(request, "Solo los agentes pueden editar propiedades.")
            return redirect('/')  # Redirige a la lista de propiedades si no es un agente

        # Verifica si el agente que está editando la propiedad es el mismo que la creo
        if propiedad.agente != request.user:
            messages.error(request, "No tienes permiso para editar esta propiedad.")
            return redirect('/')  # Redirige a la lista de propiedades si no tiene permiso

        # Si el usuario tiene permisos, continúa con el flujo normal
        return super().dispatch(request, *args, **kwargs)
            
class EliminarPropiedadView(DeleteView):
    model = Propiedad
    template_name = "eliminar_propiedad.html"
    success_url = reverse_lazy('mis_propiedades')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["propiedades"] = Propiedad.objects.all()
        return context


    def dispatch(self, request, *args, **kwargs):
        propiedad = self.get_object()


        if not request.user.is_agente:  
            messages.error(request, "Solo los agentes pueden eliminar propiedades.")
            return redirect('/')  


        if propiedad.agente != request.user:
            messages.error(request, "No tienes permiso para eliminar esta propiedad.")
            return redirect('/') 

 
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        messages.success(request, "La propiedad ha sido eliminada exitosamente.")
        return super().delete(request, *args, **kwargs)


class ContactarAgenteView(LoginRequiredMixin,TemplateView):
    template_name = 'contactar_agente.html'
    login_url = "/login/"
    redirect_field_name = "redirect_to"
    raise_exception = False

    def get(self,request):
        return self.render_to_response({})
    
class MisPropiedadesView(ListView, LoginRequiredMixin):
    model = Propiedad
    template_name = "mis_propiedades.html"
    context_object_name = 'propiedades'
    def get_queryset(self):
        return Propiedad.objects.filter(agente=self.request.user)
    
    def dispatch(self, request, *args, **kwargs):

        if not request.user.is_agente:
            messages.error(request, "No tienes permiso para acceder a mis propiedades.")
            return redirect('/')  
        

        return super().dispatch(request, *args, **kwargs)

def obtener_barrios(request):
    url = "https://cdn.buenosaires.gob.ar/datosabiertos/datasets/barrios/barrios.geojson"
    
    try:
        response = requests.get(url, timeout=5)
        response.raise_for_status()  # tira excepción si no es 200 OK
        data = response.json()

        # Ordenar los barrios alfabéticamente
        data['features'].sort(key=lambda f: f['properties']['BARRIO'])

        return JsonResponse(data)
    except (requests.RequestException, ValueError) as e:
        return JsonResponse({'error': 'No se pudo obtener los barrios', 'detalle': str(e)}, status=500)

apps/propiedad/templates/carga_propiedad.html
{% extends 'base.html' %}
{% load static cloudinary%}

{% block title %}ANDO BUSCANDO | Subir Propiedad{% endblock %}
{% block content %}
<div class="page-head"> 
  <div class="container">
      <div class="row">
          <div class="page-head-content">
              <h1 class="page-title">Publica una propiedad</h1>               
          </div>
      </div>
  </div>
</div>
<!-- End page header -->
<div class="content-area submit-property" style="background-color: #FCFCFC;">&nbsp;
  <div class="container">
      <div class="clearfix" > 
          <div class="wizard-container"> 

              <div class="wizard-card ct-wizard-orange" id="wizardProperty">
                <form method="post" enctype="multipart/form-data">                        
                  {% csrf_token %}
                  {% if form.errors %}
                  <div class="alert alert-danger">
                      <ul>
                          {% for field in form %}
                              {% for error in field.errors %}
                                  <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                              {% endfor %}
                          {% endfor %}
                      </ul>
                  </div>
              {% endif %}
              <div class="wizard-header">
                <h3>
                  <b>Carga</b> UNA PROPIEDAD <br>
                  <small>En tres simples pasos podrás publicarla.</small>
                </h3>
              </div>
              <ul>
                <li><a href="#step1" data-toggle="tab">Paso 1 </a></li>
                <li><a href="#step2" data-toggle="tab">Paso 2 </a></li>
                <li><a href="#step3" data-toggle="tab">Finalizar </a></li>
            </ul>
            <div class="tab-content">

              <div class="tab-pane" id="step1">
                  <div class="row p-b-15  ">
                      <h4 class="info-text"> Empecemos con la informacion basica</h4>
                      <div class="col-sm-4 col-sm-offset-1">
                          <div class="picture-container">
                              <div class="picture">
                                <img src="" class="picture-src" id="wizardPicturePreview" style="height: 100%;" title=""/>
                                <input type="file" name="foto" accept="image/*" id="wizard-picture" required>
                              </div> 
                          </div>
                      </div>
                      <div class="col-sm-6">
                          <div class="form-group">
                            <label for="id_titulo">Título :<small>(requerido)</small></label>
                            <input type="text" name="titulo" maxlength="50" class="form-control" required>
                          </div>
                          <div class="form-group">
                            <label for="id_moneda">Precio de la propiedad :<small>(requerido)</small></label>
                            <select name="moneda" class="form-control" required>
                              <option value="USD">USD</option>
                              <option value="ARS">ARS</option>
                            </select>
                            <input type="number" name="precio" step="0.01" required placeholder="3330000" class="form-control">
                          </div>
                          <div class="form-group">
                              <label>Tipo de operacion <small>(requerido)</small></label>
                              <select id="basic" class="form-control" name="tipo_operacion">
                                  <option disabled selected> Operacion </option>
                                  <option value="1">Alquiler</option>

                                  <option value="2">Compra</option>
                                
                                  <option value="3">Venta</option>
                              </select>
                          </div>
                      </div>
                  </div>
              </div>
              <!--  End step 1 -->

              <div class="tab-pane" id="step2">
                  <h4 class="info-text"> Contanos un poco mas sobre la propiedad </h4>
                  <div class="row">
                      <div class="col-sm-12"> 
                          <div class="col-sm-12"> 
                              <div class="form-group">
                                <label for="id_descripcion">Descripcion :</label>
                                <textarea name="descripcion" class="form-control" required></textarea>
                              </div> 
                          </div> 
                      </div>

                      <div class="col-sm-12">
                          <div class="col-sm-6">
                              <div class="form-group">
                                  <label for="id_barrio">Barrio :</label>
                                  <select name="barrio" id="barrio-select" class="selectpicker" data-live-search="true" data-live-search-style="begins">
                                    <option value="" selected disabled>Barrio</option>
                                </select>
                              </div>
                          </div>
                          <div class="col-sm-6">
                              <div class="form-group">
                                <label for="id_direccion">Dirección :<small>(requerido)</small></label>
                                <input type="text" name="direccion" maxlength="55" class="form-control" required>
                              </div>
                          </div>
                      </div>
                      <div class="col-sm-12 padding-top-15">                                                   
                          <div class="col-sm-6">
                              <div class="form-group">
                                <label for="id_tipo_propiedad">Tipo propiedad :</label>
                                <select name="tipo_propiedad" class="form-control" required>
                                  <option value="" selected disabled>---------</option>
                                  {% for tipo in form.tipo_propiedad.field.queryset %}
                                        <option value="{{ tipo.id }}">{{ tipo.tipo_propiedad }}</option>
                                    {% endfor %}
                                </select>
                              </div>
                          </div>
                          <div class="col-sm-6">
                              <div class="form-group">
                                  <label for="id_metros_cuadrados">Metros cuadrados de la propiedad (m2) :</label>
                                  <input type="number" name="metros_cuadrados" required class="span2" value="" min="0" 
                                  data-slider-max="1200" data-slider-step="1" 
                                  data-slider-value="70" id="property-geo" ><br />
                           <b class="pull-left color">20m2</b> 
                           <b class="pull-right color">1200m2</b>
                              </div>
                          </div>
                          <!-- <div class="col-sm-6">
                              <div class="form-group">
                                  <label for="property-images">sube mas imagenes : (Proximamente)</label>
                                  <input class="form-control" type="file" id="property-images" disabled>
                              </div>
                          </div> -->
                      </div>
                      <div class="col-sm-12 padding-top-15">
                          <div class="col-sm-6">
                              <div class="form-group">
                                  <label for="id_ambientes">ambientes:</label>
                                  <input type="number" name="ambientes" required class="span2" value="" min="0" 
                                         data-slider-max="20" data-slider-step="1" 
                                         data-slider-value="5" id="min-baths" ><br />
                                  <b class="pull-left color">1</b> 
                                  <b class="pull-right color">20</b>
                              </div>
                          </div>
<!--
                          <div class="col-sm-6">
                              <div class="form-group">
                                  <label for="id_metros_cuadrados">Metros cuadrados de la propiedad (m2) :</label>
                                  <input type="number" name="metros_cuadrados" required class="span2" value="" min="0" 
                                  data-slider-max="1200" data-slider-step="1" 
                                  data-slider-value="70" id="property-geo" ><br />
                           <b class="pull-left color">20m2</b> 
                           <b class="pull-right color">1200m2</b>
                              </div>
                          </div> -->
                      </div>

                      
                      
                      <br>
                  </div>
              </div>
              <!-- End step 2 -->



              <div class="tab-pane" id="step3">                                        
                  <h4 class="info-text"> Finalizar y publicar </h4>
                  <div class="row">  
                      <div class="col-sm-12">
                          <div class="">
                              <p>
                                  <label><strong>Terminos y condiciones:</strong></label>
                                  Al aceptar los terminos y condicones estas accediendo a
                                  que AndoBuscando comparta tu propiedad e informacion 
                                  personal.
                              </p>

                              <div class="checkbox">
                                  <label>
                                      <input type="checkbox" required /> <strong>Aceptar terminos y condiciones.</strong>
                                  </label>
                              </div> 

                          </div> 
                      </div>
                  </div>
              </div>
              <!--  End step 4 -->
              <div class="wizard-footer">
                <div class="pull-right">
                    <input type='button' class='btn btn-next btn-primary' name='next' value='Siguiente' />
                    <!-- <input type='button' class='btn btn-finish btn-primary ' name='finish' value='Finalizar' /> -->
                    <input type='submit' class='btn btn-finish btn-primary ' name='finish' value='Finalizar' /> <!-- El botón tiene que ser tipo "submit" para enviar -->
                </div>

                <div class="pull-left">
                    <input type='button' class='btn btn-previous btn-default' name='previous' value='Anterior' />
                </div>
                <div class="clearfix"></div>                                            
            </div>
                          </form>
            </div>
          </div>
      </div>              
  </div>                 
</div>

{% endblock %}

apps/propiedad/templates/contactar_agente.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ANDO BUSCANDO | Contactar Usuario{% endblock %}

{% block content %}

 <div class="page-head"> 
            <div class="container">
                <div class="row">
                    <div class="page-head-content">
                        <h1 class="page-title">Contactar Agente</h1>               
                    </div>
                </div>
            </div>
        </div>
        <!-- End page header -->

        <!-- property area -->
        <div class="content-area recent-property padding-top-40" style="background-color: #FFF;">
            <div class="container">  
                <div class="row">
                    <div class="col-md-8 col-md-offset-2"> 
                        <div class="" id="contact1">                        
                            <div class="row">
                           
                            </div>
                            <!-- /.row -->
                            
                            <h2>Chat</h2>
                            <form>
                                <div class="row">                                
                                    <div class="col-sm-12">
                                        <div >
                                            <label for="subject">Título</label>
                                            <input type="text" class="form-control" id="subject">
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="message">Mensaje</label>
                                            <textarea id="message" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-sm-12 text-center">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Enviar mensaje</button>
                                    </div>
                                </div>
                                <!-- /.row -->
                            </form>
                        </div>
                    </div>    
                </div>
            </div>
        </div>

{% endblock %}

apps/propiedad/templates/eliminar_propiedad.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ANDO BUSCANDO | Eliminar propiedad{% endblock %}

{% block content %}
<div class="page-head"> 
    <div class="container">
        <div class="row">
            <div class="page-head-content">
                <h1 class="page-title">Eliminar propiedad</h1>               
            </div>
        </div>
    </div>
</div>

<div class="d-flex justify-content-center align-items-center" style="background-color: rgb(249, 249, 249); min-height: 60vh; display: flex; text-align: center; justify-content: center; align-items: center;">
    <div class="register-area" style="background-color: rgb(249, 249, 249); width: 100%; padding: 20px;">


    <h2>¿Estás seguro/a que deseás eliminar la propiedad de forma permanente?</h2>
    <br>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Eliminar propiedad</button>
      <a href="{% url 'propiedades' %}" class="btn btn-secondary">Cancelar</a>
    </form>


    </div>
</div>
{% endblock %}